### ISSUE TITLE
Working to support interaction with newer XMLS

### ISSUE THREAD

**Issue by rpgoldman** [cl-openid/cl-openid#1]
Since XMLS v 2 (we're now on 3), it has parsed XML into structures, rather than lists (and for backwards-compatibility, provides the `nodes->nodelist` function).

I wanted to provide a patch that would update cl-openid to deal with this, but to be honest, I'm boggled by the existing code with its references to the `CARs` and `CDRs` of parsed XML.  Indeed, this is why XMLS changed to offer functions like `node-children`, `node-tag`, and so forth.

Would it be possible to annotate the code with some comments to indicate what parts of the XML you are trying to extract in various places?  If you could do this, I could provide a patch that will make it work.

**Comment by avodonosov** [comment]
@rpgoldman I can't comment the code - didn't write it, only reviewed briefly long ago. Only if @mpasternacki  comments.

Why not just use old XMLS?

How do you use cl-openid?

**Comment by avodonosov** [comment]
@rpgoldman, I understood. You maintain XMLS and you change the public API so that dependent libraries is broken so now you want to go and fix the dependent libraries.

It would be easier if you keep the old XMLS as is, and deliver new API in ASDF new system and package, for example XMLS2. Or use the same ASDF system and package, but extend the API instead of breaking it. If there was a function `parse` which returned a list, leave the function as is. Introduce new function `sparse` which returns structures.

That way those who want to use new API use new version, while old libraries remain working without any extra effort.

**Comment by rpgoldman** [comment]
I'm sorry: I am simply not going to do that.  I don't intend to leave around broken software just so that three libraries in Quicklisp don't have to change.  It's too much work for me, and it's not even the right thing to encourage people to use broken software.  Almost all software eventually either dies or changes its API.

Counter-suggestion:  If people really don't like the new API, they can just use the old version of XMLS, or fork it to something like "classic-xmls" and work with that.  I'm already maintaining XMLS as a volunteer: it's unfair to also ask me to maintain an old version of it, as well.

The API has changed, yes, but it has improved: it allows meaningful, named access to components of the XML representation structure, and even allows one to wrap old uses in `nodes->nodelist` function calls to maintain the old return value structure.  Looking at the code in cl-openid makes it clear why these changes were needed: the code there makes cryptic references to elements of lists with no indication of what the list structures represent, or what a particular element of the list structure refers to in the underlying XML document.

**Comment by avodonosov** [comment]
@rpgoldman, I don't suggest any of that. My proposal is a zero effort solution, which will leave everything working while allowing software to evolve to the new, better API. In contrast to the strange backward compatibility approach you try to use, when you break things, then search for clients depending on XMLS, demand work from them and do extra work yourself.

> it's not even the right thing to encourage people to use broken software. 

Don't encourage, discourage, say "Bad API, unmaintained, use XMLS2 instead" or "use this new function instead"

> I'm already maintaining XMLS as a volunteer: it's unfair to also ask me to maintain an old version of it, as well.

Don't maintain, just leave it as is.

**Comment by rpgoldman** [comment]
Look, I'm sorry, but this is already done, other software is already updated, and I'm not willing to break *that* software to make software that won't adapt to the new version work.

If that means that cl-openid won't work, of that xmls won't get upgraded in QL, fine. I'm going to close this ticket and forget about it.

**Comment by avodonosov** [comment]
It's sad that such simple mistakes lead to blasts of destruction in the CL ecosystems which take years to recover from, or more realistically, never fully recovered.
